---

  # Configurações do servidor mysql
  - hosts: database
    become: true
    become_user: root
    
    roles: 
      - update
      - mysql 

  # Configurações do servidor wordpress
  - hosts: wordpress
    become: true
    become_user: root

    roles:
      - update
      - webserver
      - wordpress
    
          
      #- name: 'copia arquivo 000-default.conf da maquina host para a maquina virtual - Configura Apache para servir o Wordpress'
      #  ansible.builtin.copy:
      #    src: 'files/000-default.conf'
      #    dest: '/etc/apache2/sites-available/000-default.conf'
      #  become: yes
      #  notify:
      #    - restart apache       