---
- hosts: all
  tasks:
    - #shell: 'echo hello > /vagrant/world.txt'
    
    - name: 'Instala o PHP5'
      apt: 
        name: php5
        state: latest
      become: yes

    - name: 'Instala o Apache2'
      apt:
        name: apache2
        state: latest
      become: yes

    - name: 'Instala o modphp'
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes