---
# Configurações do Wordpress
- name: 'Download wordpress'
  get_url:
    #url: 'https://wordpress.org/latest.tar.gz'
    url: 'https://br.wordpress.org/wordpress-5.0-pt_BR.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
    # mode: '0440' permissões de leitura e escrita

- name: 'Descompactar arquivo wordpress.tar.gz'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: 'Faz uma cópia do arquivo wp-config-sample.php como wp-config.php'
  ansible.builtin.copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura wp-config.php com as entradas do banco de dados'
  ansible.builtin.replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'nome_do_banco_de_dados_aqui', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_username }}" }
    - { regex: 'nome_de_usuario_aqui', value: "{{ wp_username }}" }
    - { regex: 'password_here', value: "{{wp_user_password}}" }
    - { regex: 'senha_aqui', value: "{{wp_user_password}}" }
    - { regex: 'localhost', value: "{{ wp_db_ip }}" }
  become: yes

# template  
- name: 'Configurara Apache para servir Wordpress (template)'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache